# This workflow will install Python and run the VocalTractLab API Python examples 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    # We need blender to run example 6
    - if: matrix.os == 'ubuntu-latest'
      name: Install blender
      run: sudo snap install blender --classic
    - if: matrix.os == 'windows-latest'
      name: Install blender
      run: |
        Invoke-WebRequest -Uri "https://ftp.halifax.rwth-aachen.de/blender/release/Blender3.0/blender-3.0.0-windows-x64.zip" -OutFile blender_setup.zip
        Expand-Archive -Path blender_setup.zip
        mkdir "D:\Program Files\Blender Foundation\Blender 3.0"
        Move-Item -Path .\blender_setup\blender-3.0.0-windows-x64\* -Destination "D:\Program Files\Blender Foundation\Blender 3.0"
    - name: Install Python dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install -r examples/requirements.txt
    - name: Build VocalTractLab API
      run: |
        mkdir tmp
        cd tmp
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --target VocalTractLabApi
    - name: Example 1 - Generates the transition from /a/ to /i/ using the vocal tract model and the function vtlSynthesisAddTract(...)
      run: |
        cd examples
        python example1.py
    - name: Example 2 - Generates the speech waveform directly from a gestural score
      run: |
        cd examples
        python example2.py
    - name: Example 3 - Obtain the volume velocity transfer function
      run: |
        cd examples
        python example3.py
    - name: Example 4 - Test synthBlock(...) function
      run: |
        cd examples
        python example4.py
    - name: Example 5 - Convert segment sequence file into a gestural score (and more)
      run: |
        cd examples
        python example5.py
    - name: Example 6 - Export vocal tract model meshes and simulated EMA points
      run: |
        cd examples
        python example6.py
