# This workflow will install Python and run the VocalTractLab API Python examples 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python examples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install YOUR_DEPENDENCIES_HERE
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build VocalTractLab API
      run: |
        mkdir tmp
        cd tmp
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --target VocalTractLabApi
    - name: Example 1: Generates the transition from /a/ to /i/ using the vocal tract model and the function vtlSynthesisAddTract(...)
      run: |
        python examples/example1.py
